### ISSUE TITLE
Extracting text from Title tag returns html tags

### ISSUE THREAD

**Issue by kristen1980** [PuerkitoBio/goquery#104]
Hi,

I have the following code:

```
package main

import (
	"bytes"
	"io/ioutil"
	"net/http"

	"github.com/PuerkitoBio/goquery"
)
import "log"

func main() {
	s := `<body>
                  <title>
			 <a href="http://example.com/" target="_blank" gbkurl="http://example.com/page1/">
			     <font color="#cc0000">this stupid font</font>
			 </a>
			this text here and there
		   </title>
		</body>`
	resp := &http.Response{Request: &http.Request{}}
	resp.Request.Method = "Get"
	resp.Body = ioutil.NopCloser(bytes.NewBufferString(s))
	doc, err := goquery.NewDocumentFromResponse(resp)
	if err != nil {
		log.Fatal(err)
	}
	title := doc.Find("title").Text()
	log.Println(title)
}

```
This prints 
```
<a href="http://example.com/" target="_blank" gbkurl="http://example.com/page1/">
<font color="#cc0000">this stupid font</font>
</a>
this text here and there
```
However, when I change the title tags to description (or just about any other tag) then search for said tag I get the expected outcome w/out html tags:

```
this stupid font

this text here and there
```

Is this a bug? (btw this isn't my html it is a page I came across from scraping the title tags of various websites).

If this is a feature is there a way to extract the text from the title tag?

**Comment by PuerkitoBio** [comment]
Hi,

That's an interesting case, the HTML parsing is done by the `golang.org/x/net/html` package, and it is strict on the tags and contents. The `title` tag is not supposed to have HTML elements inside (in addition to not being in the head) (https://www.w3.org/TR/html4/struct/global.html#h-7.4.2), so that's what happens here, the whole content is returned as if it was the text inside the tag. If you change it for e.g. `hr`, which is not supposed to have *any* content, it doesn't return anything. And if you change it for e.g. `p`, which can contain elements, then it works as expected.

`description` is not a known tag so it probably doesn't apply any restriction.

I can't think of a good simple workaround at the moment, given that this happens at a lower-level than goquery, the node returned from the `net/html` package is just a node with the `Data` field set to this, instead of having child nodes. I guess you could try to use `net/html` to parse the content of the title as an HTML fragment (https://godoc.org/golang.org/x/net/html#ParseFragment) and then grab the Data field from any Text node types, haven't tried it though. Another option would be to use the low-level `Tokenizer` from the same `net/html` package.

Please let me know if you try it and it works, I may add it to the wiki as a known gotcha or something.

Thanks,
Martin

**Comment by kristen1980** [comment]
Thanks for the quick response! Maybe I can just rename the title tag to something else then get the text from that. How do I do that?

**Comment by PuerkitoBio** [comment]
You'd have to do that *prior* to creating the goquery document. If you get the html from an http.Response.Body, you'll have to buffer it (e.g. read it in a bytes.Buffer). If you don't care too much about potential edge cases, you can then do a search / replace of the title tag with regexp (but remember: http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags :), and finally create the goquery document with NewDocumentFromReader, passing in the updated bytes, e.g. (warning: untested code):

```
var buf bytes.Buffer
// handle errors!
io.Copy(&buf, res.Body)
res.Body.Close()

re := regexp.MustCompile(`(?i)<\s*title>`)
updated := re.ReplaceAllString(buf.String(), "<nottitle>")
re = regexp.MustCompile(`(?i)</\s*title>`)
updated = re.ReplaceAllString(updated, "</nottitle>")

doc, err := goquery.NewDocumentFromReader(strings.NewReader(updated))
// handle err, use doc
```

For something more robust you could use the stdlib's XML parser with the special settings that make it handle html: https://golang.org/pkg/encoding/xml/#Decoder.

**Comment by kristen1980** [comment]
I think the below should work, though I'd appreciate feedback. Basically, you wrap the text in another tag and then extract the text from that.

```
extractText(doc.Find("title").Text())

func extractText(txt string) string {
		p := "p"
		txt = fmt.Sprintf(`<%v>%v</%v>`, p, txt, p)
		resp := &http.Response{Request: &http.Request{}}
		resp.Body = ioutil.NopCloser(bytes.NewBufferString(txt))
		doc, err := goquery.NewDocumentFromResponse(resp)
		if err != nil {
			log.Fatal(err)
		}
		return doc.Find(p).Text()
	}
```

**Comment by PuerkitoBio** [comment]
Yes, that's a better solution. Note that you don't have to create a dummy http response, just use NewDocumentFromReader and strings.NewReader(str).
