### ISSUE TITLE
Selection Node ordering guarantees.

### ISSUE THREAD

**Issue by RayfenWindspear** [PuerkitoBio/goquery#108]
As of jQuery 1.3.2, the selection array is returned in a deterministic order. Is this the case with goquery? I have an application I am porting to Go that relies on this ordering guarantee. Well, more specifically, I create templates for DOM traversal in the browser with jQuery that are consumed by my backend using goquery.

**Comment by RayfenWindspear** [comment]
Another thing I wanted to comment on. I realize that the goquery Document and a browser's DOM from the same site may have differences. My question is simply, will running the same selection on the same Document ALWAYS produce the same ordering of results?

**Comment by PuerkitoBio** [comment]
Hello Rayfen,

That's a good question, from a quick look, goquery only uses deterministic looping (i.e. slices, no maps), so it probably boils down to whether or not the net/html and cascadia packages are deterministic. I'd be very surprised if the html parser wasn't, since it is common in HTML documents to rely on such things (e.g. nth-child selectors and all), but I haven't seen anything that confirms this from this package's godoc, you'd have to peek at the code if you need a stronger guarantee.

Same goes for cascadia, though it looks like it matches by recursively calling `matchAllInto` (https://github.com/andybalholm/cascadia/blob/master/selector.go#L66) which loops in deterministic order (as long as the html parser gives nodes in a deterministic order).

Hope this helps,
Martin

**Comment by RayfenWindspear** [comment]
Thanks for the detailed response. I would also imagine that the net/html package would need to preserve order, or things could easily get misplaced and leave you with an entirely different layout. I'll take a look into cascadia to see how they handle things.

In a previous revision of Go, maps were actually deterministic in their range iteration orderings, and some goofs were actually relying on it. The Go team has since made them non-deterministic in order to discourage such bad practice.
