### ISSUE TITLE
Why use functions instead of standard jQuery string

### ISSUE THREAD

**Issue by suntong** [PuerkitoBio/goquery#110]
Hi, 

Just curious, why `goquery` chooses to use functions (e.g., `Parent()`, `First()` etc ) instead of standard `jQuery` string like "`:parent`", "`:first-child`" etc? 

The reason that I'm asking is https://github.com/andrew-d/goscrape/issues/10, i.e., `goscrape` only allows to use a single string as the "Selector", so if I can't use  `jQuery` string like "`:parent`", "`:first-child`", there are a good chuck of cases I cannot scrap with `goscrape`. 

Thanks

**Comment by PuerkitoBio** [comment]
Hello,

:first-child is a css pseudo-class, it should work as long as cascadia, the css selector package used by goquery, supports it. I haven't tried it, but I know :nth-child works, which should be equivalent (:nth-child(1)).

:parent is a jquery extension, it is not a css selector, so I doubt cascadia supports it (you can give it a shot). It is provided as a function because goquery provides the jquery-ish interface, but it doesn't parse the selectors, those are passed as-is to cascadia. I don't know the goscrape package, I can't help you for that, but to answer your question, that's why goquery provides the functions but not the selector extensions.

Hope this helps,
Martin
