### ISSUE TITLE
Can't work with root selector

### ISSUE THREAD

**Issue by anacrolix** [PuerkitoBio/goquery#117]
After getting a Selector from .Find, I want to refer to the root element in a further Find. The following don't work:

```
:root > li:nth-child(2)
> li:nth-child(2)
```

Perhaps I'm attempting this incorrectly, but I've seen both methods referred to elsewhere with jquery and css selectors in general.

**Comment by PuerkitoBio** [comment]
Hello Matt,

Goquery uses the `cascadia` package as selector engine, but it looks like it doesn't support the `:root` pseudo selector (https://github.com/andybalholm/cascadia/blob/master/parser.go#L420). It should be fairly straightforward to add it in a PR though, I may give it a shot.

Martin

**Comment by PuerkitoBio** [comment]
I take that back, it's not that straightforward because it changes the context in which the selector is applied (instead of being applied to the node passed to Match or MatchFirst, it is applied to the root html node for the rest of the selector). This impacts the design of the package (the `Selector` function signature currently cannot change the matched node), so you should probably open an issue on the cascadia repo to discuss it with Andy if you want this feature added.
