### ISSUE TITLE
Please add tag for current version

### ISSUE THREAD

**Issue by msoap** [PuerkitoBio/goquery#118]
This need for save goquery to vendor with fixed version.
Last tag - v0.3.2 too old.

**Comment by PuerkitoBio** [comment]
Hello Sergey,

I stopped using version tags because the `vendor` solution is the right one for applications using goquery anyway (especially now that Go has built-in support for this), but I don't understand why you say this is needed to vendor it with a fixed version? The vendoring tools that I know all support this without any kind of tag/semantic versioning (e.g. Godep, gvt, govendor). Those will install a version and stick to this version unless you explicitly update the vendored dependency.

Is there a use-case or a vendoring tool that behaves differently that I'm missing?

Martin

**Comment by msoap** [comment]
Versions uses in [glide](https://glide.sh/) tool.
For example `glide.yaml` with tag:
```
import:
- package: github.com/PuerkitoBio/goquery
  version: v0.3.3
```

instead with hashsum
```
import:
- package: github.com/PuerkitoBio/goquery
  version: 77cbaef46a3af185a3afb87f88a366f3dee2a904
```

**Comment by PuerkitoBio** [comment]
Ok so it looks like it works like other tools, you can still fix a version with the hash. I'd suggest using this option, because none of the dependencies of goquery (cascadia and net/html) use version tags, so you'd end up needing to put hashes in there anyway.

**Comment by msoap** [comment]
Ok, I will use a hash.

**Comment by PuerkitoBio** [comment]
Just to let you know, the tag request came back, so I tagged the latest as v1.0.0 and will follow semver from now on.
