### ISSUE TITLE
If there have dot in id selector,goquery can't parse it correctly

### ISSUE THREAD

**Issue by fzypzl** [PuerkitoBio/goquery#119]
If there have dot in id selector,goquery can't parse it correctly
eg #my.content

**Comment by PuerkitoBio** [comment]
The dot indicates a class name, so it gets parsed as `id=my` and `class=content`. According to this, in jquery you can escape the dot so that it finds the id correctly : http://stackoverflow.com/questions/605630/how-to-select-html-nodes-by-id-with-jquery-when-the-id-contains-a-dot

Haven't tested if it works with cascadia, the selector engine used by goquery. Otherwise, you can try the attribute selector e.g. `"[id='my.content']"`.

**Comment by fzypzl** [comment]
Think you very much!
 I use attribute selector,It works.
 I will try to escape the selector.
