### ISSUE TITLE
How to replace text within some tag

### ISSUE THREAD

**Issue by Komosa** [PuerkitoBio/goquery#123]
Hi,
I want to postprocess static HTML (created by me).
Let's say that we have `<h1 class="message">placeholder</h1>` as part of document, and I want to replace `placeholder`, my selector is `.message`.

Currently I see only one option: use  `ReplaceWithHTML`, but it needs to:
- know, that used tag is _h1_;
- or figure it out via `NodeName` function - it seems unnecessarily complicated to construct replacement string in that way.
Both options needs to copy also all atributes.

I hope that I missed cleaner method, could you point it?

**Comment by PuerkitoBio** [comment]
Hello,

The initial (and still the main AFAIK) use-case of goquery is to scrape HTML pages, so that's why most of the "modification/setter" APIs are not implemented. Over the years some people had uses for such methods, and they contributed the Replace/Wrap/Append/etc. methods.

What you're looking for, I believe, is the equivalent of jquery's `.text(string)` and `.html(string)`, that replace the content (innerText or innerHtml) of all selected elements with the provided string (html-escaped for `text()`). If someone is interested in contributing that to goquery, with the same semantics as jquery (i.e. all selected elements have their contents replaced), I'm definitely open to merge such a PR. It would probably be `*Selection.SetText(string) *Selection` and `*Selection.SetHtml(string) *Selection`. Bonus points for `SetTextFunction(func(int, string) string)` and `SetHtmlFunction(...)` (the equivalent of http://api.jquery.com/html/#html-function).

But for now, as you've mentioned, there is no clean way to do this.

Hope this helps explaining why some parts are missing,
Martin

**Comment by Komosa** [comment]
Thank you for explanation :)

**Comment by Komosa** [comment]
Just to note, there is simpler method for my simple (and, I think, common when editing html) case.

    selector := ".message > *" // get all (in my case, the only one) children of .message
    elem := doc.Find(selector)
    elem.ReplaceWithHtml(newContent) // newContent contains just plain text to be inserted in

Code above will select text/data inside of _h1_ tag from first message.
