### ISSUE TITLE
cannot parse this html

### ISSUE THREAD

**Issue by KlonD90** [PuerkitoBio/goquery#129]
http://www.75.fsin.su/news/detail.php?ELEMENT_ID=273811
*errors.errorString <nil>
/usr/lib/go/src/runtime/asm_amd64.s:1998
throw panic with this error.

I don't have any idea how to debug it in right way.

**Comment by PuerkitoBio** [comment]
What line of code triggers that error? The line you pasted is in the runtime, what would be useful is the userland code that calls this.

In any case, I can get it to load in a goquery document with this code:

```
func main() {
	req, err := http.NewRequest("GET", "http://www.75.fsin.su/news/detail.php?ELEMENT_ID=273811", nil)
	if err != nil {
		log.Fatal(errors.Wrap(err, "new request"))
	}
	req.Header.Set("User-Agent", "Mozilla/5.0 (Maemo; Linux armv7l; rv:10.0.1) Gecko/20100101 Firefox/10.0.1 Fennec/10.0.1")

	res, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatal(errors.Wrap(err, "get"))
	}
	if res.StatusCode >= 400 {
		log.Fatalf("status %d %s", res.StatusCode, res.Status)
	}

	b, err := ioutil.ReadAll(res.Body)
	if err != nil {
		log.Fatal(errors.Wrap(err, "read all"))
	}
	log.Printf("%s", b[:100])

	_, err = goquery.NewDocumentFromResponse(res)
	if err != nil {
		log.Fatal(errors.Wrap(err, "new doc"))
	}
}
```

Some interesting bits: you have to set some browser user-agent string otherwise it doesn't return anything, and the encoding is windows-1251 so you *will* have issues decoding it. You have to transform it to utf8 before parsing it with goquery. See the wiki for some hints on how to do that.
