### ISSUE TITLE
can't properly iterate children tags and tags named <Image>

### ISSUE THREAD

**Issue by dansouza** [PuerkitoBio/goquery#130]
I have been using goquery to read some simple XML documents successfully so far, until now. The XML in the reference code is a cut-out of a larger XML document that I can work on successfully, except for this particular snippet that deals with a list of images.

OUTPUT: http://pastebin.com/sVqWHiwf
CODE: http://pastebin.com/4TVLCStA

1) Why can't I properly iterate over the `Image` tags and their URLs?
2) Why are the tags changing from `Image` to `img` ?

**Comment by PuerkitoBio** [comment]
Hello Dan,

Yeah this is the behaviour of the Go html5 parser, if you run this with your XML as input:

```
func main() {
	n, err := html.Parse(strings.NewReader(input))
	if err != nil {
		log.Fatal(err)
	}
	html.Render(os.Stdout, n)
}
```

It prints the output that you see. Goquery relies on those parsed nodes, so that's why you have those issues. Being an html parser, it assumes the input is html and it is probably part of the reference parser doc to replace `<image>` with `<img>` (because those are treated as synonyms by browsers, according to http://stackoverflow.com/questions/11928566/img-vs-image-tag-in-html).

And then, because `<img>` can't have any content (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img), the content is moved outside the tag.

You'd really want to use an xml parser for this. It would be nice to have goquery support an xml parser instead of the html one for cases like this, and then be able to use the jquery functions to navigate the doc, but xml is a beast with many dark corners, it would probably be a bad idea. I'd suggest something like https://github.com/moovweb/gokogiri or https://godoc.org/gopkg.in/xmlpath.v2 for a pure go xpath implementation.

**Comment by dansouza** [comment]
I see. Thank you for taking the time to explain it. I'll look into using proper XML parsers for it, although I was enjoying using GoQuery for that!
