### ISSUE TITLE
css selector manipulation

### ISSUE THREAD

**Issue by sdwarwick** [PuerkitoBio/goquery#133]
Since html has an attribute "Style"  it would seem nice to have access to a .CSS() function to enable setting and removing styles in this specific attribute.  It would not be necessary to do checking for validity, but would seem to be a nice convenience rather than every time having to roll your own functions.

**Comment by PuerkitoBio** [comment]
Hello,

Unless I misunderstand what you mean, take a look at `Attr` and `SetAttr`, no need to roll out your own functions.

Martin

**Comment by sdwarwick** [comment]
yes,  it is different.   given:

 `<p style='display:none ; color:black' > `

it is possible to do something like:  
```
Find("P").css('display')  to get just the display style
Find("P").css('display','visible')  to change the display style
```

this requires parsing the style attribute looking for semicolons etc., but is a very common use case

**Comment by PuerkitoBio** [comment]
Ok I see what you mean (like the css jquery method - when you said no need to check for validity I thought you meant not parsing the style property at all).

It wouldn't be that useful in practice, because unlike jquery, which returns the computed style property (ie not just what was set via the style attribute directly on the node, but what is currently set even if it is via css selectors or javascript), the goquery version would only have access to whatever's directly set on the style attribute, which could be not only frustrating, but also misleading.

**Comment by sdwarwick** [comment]
yes, I ended up creating the equivalent of something more general "subAttr"  which made it more general..  subAttr('style','display')

I don't think people would be confused..  I don't think people see these libraries as being equivalent to a true DOM processor, only an HTML parser
