### ISSUE TITLE
Best way to emulate createElement() and then setInnerHTML()?

### ISSUE THREAD

**Issue by lox** [PuerkitoBio/goquery#134]
I'm trying to support some JS code that does a createElement for an empty div and then replaces it with an `<a href="">` via SetInnerHTML(). Yes, this is terrible, but is there a way to translate it into goquery?

Currently I am replicating createElement with AppendHtml(), and then using ReplaceWithHtml() to replace it for the SetInnerHTML(). Is there a better way? Also, what's the easiest way to get a selection with the appended piece after AppendHtml()?

**Comment by PuerkitoBio** [comment]
Hello Lachlan,

A couple things are not totally clear for me, why do you create an empty div to then replace it with an anchor? And by `SetInnerHTML` I assume you mean setting the `innerHTML` property? So what the js does is create a div and set its content to an anchor, it doesn't actually replace the div?

You can certainly use `AppendHtml` to add a node to a selection, though you could add the div with its inner anchor immediately in one go instead of using `Replace` afterwards. You can also create the `*html.Node` directly, and use `AppendNodes`. Then you can use `FindNodes` to select the appended node.

An example would help make sure I correctly understand what you're trying to achieve, though.

Martin
