### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by zhiephie** [PuerkitoBio/goquery#135]
```
if doc, e = goquery.NewDocument(fmt.Sprintf("https://example.com")); e != nil {
		panic(e.Error())
	}

	doc.Find("ol.list li").Each(func(i int, s *goquery.Selection) {
		// title := s.Find("h3 a").Text()
		split := s.Find("h3 a").Text()
		owner := strings.Split(split, "/")
		description := s.Find("p.col-9").Text()
		url := s.Find("h3 a").Attr("href")
Box := Trending{
	fruits:        []string{"apple", "peach", "pear"},
	owner:       string(strings.TrimSpace(owner[0])),
	title: 		 string(strings.TrimSpace(owner[1])),
	url:		 string(url),
	description: string(description),
}
res1B, _ := json.Marshal(Box)
fmt.Println(string(res1B))
}
```

result `{}`

**Comment by PuerkitoBio** [comment]
Hello Yudi,

Many things are wrong. The title of the issue doesn't describe an issue. You just pasted an incomplete, unformatted block of code, assuming I'd just parse it and figure everything out for you. This is not the way to ask for support or to report a bug.

That said, I'll give you a hint. You json-encode a value of the `Trending` struct, and all (assigned) fields are unexported. Maybe it does satisfy the `json.Marshaler` interface, but I can't tell since the struct's definition is missing. This is quite likely totally unrelated to goquery.

Martin
