### ISSUE TITLE
How can i get the manipulated representation?

### ISSUE THREAD

**Issue by heart4hackers** [PuerkitoBio/goquery#146]
Hi,

i was reading over the API and tests, and I still have no idea how I can run manipulations on documents like remove etc. and get the final, manipulated html from the document?

Can you help me out?

Best,

**Comment by PuerkitoBio** [comment]
Hello,

Most methods that modify the DOM tree were not initially implemented because unlike in jQuery, goquery works with static nodes, not a live DOM. However some users have been interested in those use-cases (modifying the nodes and re-rendering the updated HTML) and have contributed some methods for this, documented in the "manipulation" methods section here: https://godoc.org/github.com/PuerkitoBio/goquery.

We now have a good collection of those, chances are your use case will be supported.

Martin
