### ISSUE TITLE
selector duplicating entry on nested <a>, when second <a> is in <div>

### ISSUE THREAD

**Issue by Marqin** [PuerkitoBio/goquery#150]
I'm trying to parse some strangely build webpage (forums), where is structure like `<a><div><a></a></div></a>` and parser seems to parse it wrong - it caches the first a multiple times, as show in my example.

```go
package main

import (
	"fmt"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

const data = `
<a class="myclass" href="/foo/bar">
  ...here is some stuff...
  <div><a href="/baz/baz">some stuff</a></div>
  ...here is also some stuff...
</a>
`

func main() {
	d, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		fmt.Println(err)
		return
	}
	d.Find("a.myclass").Each(func(i int, s *goquery.Selection) {
		href, ok := s.Attr("href")
		if ok {
			fmt.Println(href)
		}
	})
}
```

This example prints:

>/foo/bar
>/foo/bar

and should:

>/foo/bar

**Comment by PuerkitoBio** [comment]
Hello Hubert,

Indeed I tried your example and got that result. It turns out that the underlying `net/html` parser used by goquery adds the superfluous `<a class="myclass">` which explains why it shows up twice. That is, if you run this code on your html excerpt:

```
        // import "golang.org/x/net/html"
	root, e := html.Parse(strings.NewReader(data))
	if e != nil {
		fmt.Println(e)
		return
	}
	html.Render(os.Stdout, root)
```

It prints this content:

```
<html><head>
  </head>
  <body>
    <a class="myclass" href="/foo/bar">
      ...here is some stuff...
      </a><div><a class="myclass" href="/foo/bar">
        </a><a href="/baz/baz">some stuff</a>
      </div>
      ...here is also some stuff...
</body></html>
```

I'm not sure why at this point, but I'm guessing something in the original html isn't quite right and the rules of the standard html5 parser kick in to fix the tags and it gives that result. Or there's a bug in the parser, from what I could understand from MDN on the `<a>` tag, those are all permitted content, if you want to open an issue on the `net/html` tracker with that information, they can probably tell you if it's expected behaviour or not (and why).

Martin

**Comment by Marqin** [comment]
They said it's how HTML parsers work with links to HTML spec: https://github.com/golang/go/issues/18865#issuecomment-276866253
