### ISSUE TITLE
proposal: Struct Tags

### ISSUE THREAD

**Issue by andrewstuart** [PuerkitoBio/goquery#151]
So I've been thinking for quite a long time that it would be awesome to be able to create structs with declarative tags for how an html document should be decoded into the struct. Much like one would do with the xml package, but using the syntax popularized by "that j-thing." 😄

So, for example:
```go
type Page struct {
	Resources []Resource `goquery:"#resources .resource"`
}

type Resource struct {
	Name string `goquery:".name"`
}

func main() {
  var p Page
  var r io.Reader
  // Get an io.Reader somehow
  goquery.NewDecoder(r).Decode(&p)
}
```

Any thoughts? Would this be something I could create a PR for?

**Comment by PuerkitoBio** [comment]
Hey Andrew,

Yeah I also thought about something like that a while ago, I think it would be interesting but I don't think it has to be in the goquery package, it could very well be another package that uses goquery to achieve this.

If you feel like giving it a shot and build that package, let me know and I'd be glad to link to it from the docs!

Thanks,
Martin

**Comment by barthr** [comment]
Sounds very cool, I would love to contribute to such package. Let me know!

**Comment by PuerkitoBio** [comment]
You may want to take a look at this repo:

https://github.com/cathalgarvey/sqrape

**Comment by barthr** [comment]
Thanks for sharing. Was looking through the code, there is a lot of reflection magic

**Comment by PuerkitoBio** [comment]
You have to use reflection to get an arbitrary struct's fields and tags, that's how it's done in the json and xml packages too. That said, I haven't looked at the code, that's not an endorsement of its quality :) just that it seems to be more or less what Andrew had in mind.

**Comment by barthr** [comment]
Yes, ofcourse. It just makes it a little bit harder to understand!

**Comment by andrewstuart** [comment]
I did actually throw together an MVP yesterday that's implemented in-tree. Shouldn't be too hard to split it out, but I'm guessing it would probably be maintained better if it was in the same repo.

Most of the logic is handled by goquery already, so I was surprised by how little I had to implement.

I'd still like to handle more than just `Selection.Text()`, (attrs and HTML for examplre) but what I have already is pretty effective, at least for inner text.

https://github.com/andrewstuart/goquery/tree/unmarshaling

https://github.com/PuerkitoBio/goquery/compare/master...andrewstuart:unmarshaling

Let me know what your thoughts are. 😄

**Comment by PuerkitoBio** [comment]
Hey Andrew,

I have to say it looks really good! A couple nitpicks:

- I'd use `strconv.ParseBool` to set a boolean value, so that it behaves as in Go (e.g. "1" and "t" is true too).
- `UnmarshalDocument` could be `UnmarshalSelection` and you can pass in a document as a selection, so you can unmarshal a specific sub-selection of a document into a struct. However that makes the `Unmarshaler` interface with its `UnmarshalSelection` method a bit confusing, would require some naming changes.
- Not sure there's much value in the `Decoder` part, as that usually means decoding a stream of values (e.g. for json or xml) whereas here it's just a document that will be decoded as a whole, the same as with `UnmarshalDocument`.

If you want to go ahead and polish it a bit (from a quick glance, maybe add some error test cases and document the public API) and submit a PR, it does look clean and useful.

Thanks!
Martin

**Comment by andrewstuart** [comment]
> However that makes the Unmarshaler interface with its UnmarshalSelection method a bit confusing, would require some naming changes.

So, originally the method I had for the `Unmarshaler` interface was just `Unmarshal(*Selection) error`, but I took a look at the `encoding/xml` and `encoding/json` interfaces, which have their methods named [UnmarshalXML](https://golang.org/src/encoding/xml/read.go?s=6425:6507#L146) and [UnmarshalJSON](https://golang.org/src/encoding/json/decode.go?s=3954:4013#L95). So I was kinda on the fence between `UnmarshalSelection` and `UnmarshalGoQuery`, and ended up going with "Selection" because it's not quite so terrible.

Now that I think about it, though, a general "UnmarshalHTML" might make the most sense, since that matches the actual data format, which is what the json/xml packages do.

**Comment by PuerkitoBio** [comment]
👍  Yeah `UnmarshalHTML` sounds good to me.

**Comment by PuerkitoBio** [comment]
Closing, see #152 for details.
