### ISSUE TITLE
Not doesn't work

### ISSUE THREAD

**Issue by tommoholmes** [PuerkitoBio/goquery#154]
I want to to get this html but not some element
I give you example
```
<article>
<span style="color:red">
hai hello world
</span>
<div class="add-content">
lalalaa
</div>
<p>
lorem ipsum lalala
</p>
</article>
```
I want to remove or not include `add-content`
I want getting html like this
```
<span style="color:red">
hai hello world
</span>
<p>
lorem ipsum lalala
</p>
```
I try use `doc.Find("article").Not("add-content").Html()` or `doc.Find("article").Remove("add-content").Html() ` and `doc.Find("article:not(#add-content")`
but not working

**Comment by PuerkitoBio** [comment]
Hello,

A couple of issues here, first to filter-out the `<div>` with the `add-content` class, you need to call `Not(".add-content")` (notice the dot in front of the name of the class). But this won't work, because `Not` filters-out the nodes in the top-level selection, and your selection at this point only has the `<article>` element, so the `Not` operator doesn't find anything to remove.

What you want is `doc.Find("article").Children().Not(".add-content")`, which selects all *children* of the `<article>` element, and then removes the `<div>` with the `add-content` class from the selection.

Have fun!
Martin

**Comment by NHOrus** [comment]
Can you put this to the documentation of Not()?

**Comment by PuerkitoBio** [comment]
Hello,

I'm always interested in ways to improve the documentation, and especially adding short examples to the documentation would certainly help for a lot of the methods. I'm happy to merge any PR that would clarify the behaviour in a succinct but unambiguous (or less ambiguous!) way (e.g. with better phrasing or short examples).

Thanks,
Martin
