### ISSUE TITLE
Html() bug

### ISSUE THREAD

**Issue by azumads** [PuerkitoBio/goquery#158]
test data:
1.  `<p class="good">STAY CONNECTED<p>456</p></p>`
2. `<p class="good">STAY CONNECTED<span>456</span></p>`

test code:

doc.Find("p.good").Each(func(i int, s *goquery.Selection) {
	val, _ := s.Html()
}

test result:
1. get  `STAY CONNECTED`
2. get  `STAY CONNECTED<span>456</span>`

**Comment by PuerkitoBio** [comment]
Hello Azuma,

The 1st html gets parsed by the html5 parser as

```
<p class="good">STAY CONNECTED</p><p>456</p><p></p>
```

because it has an invalid structure (`<p>` within an unclosed `<p>`). Or more accurately, the initial `<p>` is automatically terminated when the subsequent starting `<p>` is encountered, as explained here: https://developer.mozilla.org/en/docs/Web/HTML/Element/p.

As such, the result you get is the expected result (and that's why it differs from the second result).

Hope this helps,
Martin
