### ISSUE TITLE
Append method ignores td th

### ISSUE THREAD

**Issue by awsong** [PuerkitoBio/goquery#178]
If I try to `Append("<th>New</th>")`, the 'th' tag is always dropped. Same for td, tr

**Comment by mna** [comment]
Hello Andy,

`Append` expects a selector string, not an HTML string (see https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Append). What you want is `AppendHtml` (https://godoc.org/github.com/PuerkitoBio/goquery#Selection.AppendHtml).

Martin

**Comment by awsong** [comment]
It's not about HTML. I tried AppendHtml, same thing. And only th, td and tr are dropped, doesn't happen to other tags.

**Comment by mna** [comment]
Please provide a minimal, complete and verifiable example (https://stackoverflow.com/help/mcve).

Thanks,
Martin

**Comment by awsong** [comment]
```
package main

import (
    "fmt"
    "log"
    "strings"

    "github.com/PuerkitoBio/goquery"
)

func ExampleScrape() {
    doc, err := goquery.NewDocumentFromReader(strings.NewReader("<html><head></head><body><thead><tr><th>First</th></tr></thead></body></  html>"))
    if err != nil {
        log.Fatal(err)
    }  

    // Find the review items
    h, _ := doc.Html()
    fmt.Println(h)
    doc.Find("thead>tr").AppendHtml("<th>New</th>")                                                                                        
    h, _ = doc.Html()
    fmt.Println(h)
}

func main() {
    ExampleScrape()
}
```

**Comment by mna** [comment]
Thanks for the example, there are two things going on here:

First, your html is invalid, you need a `<table>` tag around the `<thead>`.

But that doesn't fully solve the issue, the `<th>` around the appended html is still stripped, and that's because of the way the html fragment is parsed. The html parser's API expects a node as context to parse a fragment, and goquery passes a generic element as context, so the `<th>` tag is deemed invalid in this context by the parser.

I'm not sure about the right fix atm, probably the current selection's node should be used as context but I need to take a closer look at this. Thanks for raising this, I'll reopen it and will try to get to it soon'ish.

Martin

**Comment by han2015** [comment]
I have the same problem about table's tr and td. have any updating? :)

**Comment by mna** [comment]
I did investigate the issue, but the problem is that the selection can contain all kinds of nodes, and `parseHtml` is currently called once with a generic element as context, and the generated nodes are used to modify all nodes in the selection.

I think it's very possible to fix this, at the cost of re-parsing the HTML nodes to append for each node in the selection (with the obvious optimization of avoiding the parsing if the context node is the same as one already processed). However it's not a trivial change, and I don't have time to dive into this right now.

If anyone is interested in giving it a try (with tests), I'd be happy to assist with code reviews and help with any questions that may come up.

Martin
