### ISSUE TITLE
goquery delivers not utf-8 HTML encoding for French characters

### ISSUE THREAD

**Issue by LeMoussel** [PuerkitoBio/goquery#184]
With the following code, I don't understand why, I don't get utf-8 HTML encoding French characters.

```
d, err := goquery.NewDocument("https://www.google.fr/search?q=golang")
nf := d.Find("h3.r a")
ct := nf.Text()
fmt.Println(utf8.ValidString(ct)) //prints: false
fmt.Println(ct) //prints: GolangGo (langage) — Wikip�diaGo (programming language) - .....
```

**Comment by mna** [comment]
Hello,

Indeed it looks like the whole data returned from that URL is not valid utf-8:

```
	res, err := http.Get("https://www.google.fr/search?q=golang")
	if err != nil {
		log.Fatal(err)
	}

	b, err := ioutil.ReadAll(res.Body)
	if err != nil {
		log.Fatal(err)
	}
	res.Body.Close()
	fmt.Printf("Returned data is utf-8? %v\n", utf8.Valid(b)) // prints false
```

According to `enca`, it is an unrecognized encoding. Goquery expects the input bytes to be valid utf-8, because that's what the underlying `net/html` parser expects.

However, if you set a well-known browser user-agent string to the request, then it returns valid utf-8. Maybe some sort of trivial protection against scraping the results.

Hope this helps,
Martin
