### ISSUE TITLE
获取中文网页有乱码的问题

### ISSUE THREAD

**Issue by zzmm1** [PuerkitoBio/goquery#185]

**Comment by mna** [comment]
Hello,

I don't speak Chinese, but according to Google Translate this would be along the lines of "Get the Chinese website has garbled problems". I will guess that you see weird characters when manipulating a page from a Chinese website with goquery.

This is very likely because the data is not utf8-encoded. The `net/html` parser used by goquery requires the input to be in utf-8. When this is not the case, it must be converted first, before passing it to goquery. See https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-non-utf8-html-pages in the wiki for an example of how to do it.

Hope this helps,
Martin

**Comment by zzmm1** [comment]
谢谢您的帮助。

**Comment by tomoya92** [comment]
i use iconv-go change encoding gb2312 to utf8. it throw an exception `illegal byte sequence`

**Comment by mna** [comment]
Hello,

I'm not familiar with the iconv-go package, but it looks like this should be raised on their repository.

Martin

**Comment by blackmatch** [comment]
@zzmm1 you can use `simplifiedchinese` package to decode gbk string, example:

```go
import (
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"

	"github.com/PuerkitoBio/goquery"
	"golang.org/x/text/encoding/simplifiedchinese"
)

func decodeToGBK(text string) (string, error) {

	dst := make([]byte, len(text)*2)
	tr := simplifiedchinese.GB18030.NewDecoder()
	nDst, _, err := tr.Transform(dst, []byte(text), true)
	if err != nil {
		return text, err
	}

	return string(dst[:nDst]), nil
}

func parseBody(body io.ReadCloser, page int) {
	// Load the HTML document
	doc, err := goquery.NewDocumentFromReader(body)
	handleError(err)

	doc.Find(".box-result h2").Each(func(i int, selection *goquery.Selection) {
		title := selection.Find("a").Text()
		gbkTitle, _ := decodeToGBK(title)
		fmt.Println(gbkTitle)

		sourceUrl, _ := selection.Find("a").Attr("href")
		gbkSourceUrl, _ := decodeToGBK(sourceUrl)
		fmt.Println(gbkSourceUrl)

		author := selection.Find(".fgray_time").Text()
		gbkAuthor, _ := decodeToGBK(author)
		fmt.Println(gbkAuthor)
	})
}
```

or you can use the package in other way anyone you want.
