### ISSUE TITLE
Goquery selection not finding element

### ISSUE THREAD

**Issue by migreva** [PuerkitoBio/goquery#187]
I'm working on scraping a webpage to find contents of elements. I have a selector that successfully finds the element via JavaScript, but goquery fails to find the element.

I've made a gist that shows the issue, which can be found here: https://gist.github.com/migreva/bfda4fed23827fc9cbb99fd204de2da2

(specifically, the panic [here](https://gist.github.com/migreva/bfda4fed23827fc9cbb99fd204de2da2#file-goquery-go-L32))

### Failing URL
https://www.whitehouse.gov/forreviewstaff-salaries
### Failing Selector
`body > *:nth-child(5) > *:nth-child(2) > *:nth-child(1) > *:nth-child(2) > *:nth-child(2) > *:nth-child(1) > *:nth-child(1)`

Here's proof of successfully finding the element on that page via JavaScript
<img width="718" alt="screen shot 2017-06-23 at 10 33 10 am" src="https://user-images.githubusercontent.com/2940659/27489359-db4d5e88-57ff-11e7-8678-d6533367f58a.png">

**Comment by migreva** [comment]
My apologies. Seems to be there's an element that gets added via JS, which is causing problems. Closing issue

**Comment by mna** [comment]
Hello Michael,

This is because the document is altered by javascript - specifically, a `<div id="nav-overlay">` is added inside the `<section>` element, which is why your selector works in javascript but not in goquery (because you only have the original page source, not the nodes added by the page via javascript).

The following selector works in goquery: 

```
// note the :nth-child(1) instead of :nth-child(2) in the third part.
"body > *:nth-child(5) > *:nth-child(1) > *:nth-child(1) > *:nth-child(2) > *:nth-child(2) > *:nth-child(1) > *:nth-child(1)"
```

However, even though it works, I'd suggest a more robust selector unless this is a one-off thing. This will fail as soon as simple layout changes are made in the page. Something like `#page h1` might be better.

Hope this helps,
Martin

**Comment by migreva** [comment]
Thanks Martin! That helps a bunch, I think I will make the selectors a little more specific to get around this issue
