### ISSUE TITLE
NewDocumentFromReader changes the order of tags

### ISSUE THREAD

**Issue by ganelon13** [PuerkitoBio/goquery#195]
{{menuDetail|safe}} rises one level higher.

```
layout := "<div><table>{{menuDetail|safe}}<tr><td>test</td></tr></table></div>"
fmt.Println(layout)

doc, err := goquery.NewDocumentFromReader(strings.NewReader(layout))
if err != nil {
	return err
}

fmt.Println(doc.Html()) 
// got <html><head></head><body><div>{{menuDetail|safe}}<table><tbody><tr><td>test</td></tr></tbody></table></div></body></html>
```

If `layout := "<div><table><tr><td>{{menuDetail|safe}}</td></tr><tr><td>test</td></tr></table></div>" 
`all is well, but I do not need an additional wrapper in `<tr><td>`. 

How can I solve it?

**Comment by mna** [comment]
Hello,

This is because that is not valid HTML, `<table>` elements cannot directly contain free text (see https://developer.mozilla.org/en/docs/Web/HTML/Element/table). The `<td>` element can, of course, which is why your alternate test works. The `net/html` parser automatically corrects the layout by taking the text outside the element.

Hope this helps, have fun with your project!
Martin

**Comment by ganelon13** [comment]
Thanks for your reply. Yes, I know it. But I need to keep this structure to later replace {{menuDetail|safe}} with array of <tr><td>  that comes from another source. Is this possible with goquery?

**Comment by mna** [comment]
No, goquery is for parsing html (internally it uses Go's `net/html` parser), not templating languages. The parser will always correct invalid html is such ways, following the rules of standard html5 parsing.

**Comment by ganelon13** [comment]
I adjusted the output doc.Html with regexp and this works fine for me. Thanks for your answers and for your package.
