### ISSUE TITLE
How to use cookies in front of goquery?

### ISSUE THREAD

**Issue by Frodgy** [PuerkitoBio/goquery#217]

**Comment by mna** [comment]
Hello,

Cookies and any web- or network-related concerns are orthogonal to goquery. Goquery cares about the HTML document parsed from a reader. My guess is that you want to crawl some site that requires some state cookies to be present to access a page, and that's the concern of your crawling package. If you use only Go's standard library, you need to create a `http.Client` configured with a `CookieJar` (a container that stores cookies in a client so that those can be sent back with subsequent requests to the same domain).

I suggest you take a look at `net/http/cookiejar`, an implementation of a Cookie jar in Go's standard library, it has a usage example: https://golang.org/pkg/net/http/cookiejar 

Martin
