### ISSUE TITLE
`Find` doesn't work without a parent container?

### ISSUE THREAD

**Issue by YamiOdymel** [PuerkitoBio/goquery#225]
Here's the reproduce example.

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	doc, _ := goquery.NewDocumentFromReader(bytes.NewBuffer([]byte(`
		<div id="a">I'm A.</div>
		<div id="b">I'm B.</div>
		<div id="c">I'm C.</div>
		<div id="d">I'm D.</div>
	`)))

	// Get the `#b`, `#c` elements.
	sel := doc.Selection.Find("#a").NextUntil("#d")

	// Output:
	// 2
	fmt.Println(sel.Length())

	// [PROBLEM] Output:
	// 0
	fmt.Println(sel.Find("#b").Length())

	// Output:
	// {0xc420060310 0xc420060540 0xc420060540 0xc420060460 0xc4200605b0 3 div div  [{ id b}]}
	fmt.Println(*sel.Nodes[0])
}

```

What I expected to see is I could find the `#b` element with `sel.Find("#b")` but it shows none (The `Length()` returns `0`).

The `fmt.Println(*sel.Nodes[0])` shows the element `#b` is in the `*sel.Nodes`, but the `Find()` function couldn't find it.

**Comment by YamiOdymel** [comment]
Okay, it seems like this is not a bug but a normal behavior.

**Comment by mna** [comment]
Hello,

As documented here: https://godoc.org/github.com/PuerkitoBio/goquery#Selection.Find, `Find` matches *descendants* with the selector. jQuery works the same way, e.g. if you open the console in the godoc page for goquery (https://godoc.org/github.com/PuerkitoBio/goquery) and run:

```
$("h4").find("#pkg-examples")
```

It doesn't match anything. That's because the "#pkg-examples" is a "h4", so it is already in the selection and is not a descendant. What you may be looking for is `Filter`, which applies the selector to the set of selected elements.

Hope this helps!
Martin

**Comment by YamiOdymel** [comment]
Hmm.. you are right, I [tried](https://jsfiddle.net/o2gxgz9r/20478/) this with jQuery again, it's the same result with goquery.

I might create a wrapper like the following code to wrap the elements to use the `Find` function. and I'll take some time to checkout the `Filter` function you mentioned, thanks.

```go
wrapper, err := goquery.NewDocumentFromReader(bytes.NewBuffer([]byte("")))
check(err)

wrapper.Find("body").AppendSelection(sel).Find("#b")
```
