### ISSUE TITLE
function each will have index out of range problem

### ISSUE THREAD

**Issue by baofengqqwwff** [PuerkitoBio/goquery#237]
hello,the problem comes from iteration.go:10,each comes from doc.Find("li").Each(func(i int, s *goquery.Selection) {}

**Comment by mna** [comment]
Hello,

Please provide a minimal but complete code example that reproduces the issue you're having, along with the expected correct result.

Thanks,
Martin

**Comment by baofengqqwwff** [comment]
thank you, my code as below.



        res := getRep(queryurl, proxyip)
	doc, err := goquery.NewDocumentFromResponse(res)
	defer  res.Body.Close()

	if err != nil {
		fmt.Println(err)
		return err
	}
	fmt.Println(doc.Text())

	local, _ := time.LoadLocation("Asia/Chongqing")
	nowTime := time.Now().In(local)

	if doc.Find("li").Length() != 0 {
		doc.Find("li").Each(func(i int, s *goquery.Selection) {  //this line will have index out of range problem
			
			name := strings.TrimSpace(s.Find("div[class=des] h2").Text())

                  .....
                  }
         }

**Comment by mna** [comment]
Hello,

Thanks for the better explanation. Unfortunately the provided code cannot be used to reproduce the issue, is it possible for you to capture the HTML used to create the goquery document when the problem arises? E.g. you can log it or save it somewhere with `goquery.OuterHtml(doc.Selection)`. And can you post the full stack trace that you get when it panics/fails? My guess is that it comes from the function that you pass to `Each`, because you mention `iteration.go:10` which is the line of the **call** of the provided function, not goquery code.

It is impossible that the index is out of range in `Each` because the function is, internally, a `range` over a Go slice. The only way this could fail is if you somehow use the `i` index with some other slice inside the function you pass to `Each`, or some concurrent access to the same `*goquery.Selection` but that doesn't seem the case from what you posted. The whole implementation of `Each` is:

```
        // f is the function you provide to Each, and it is line 10 in iteration.go
	for i, n := range s.Nodes {
		f(i, newSingleSelection(n, s.document))
	}
```

And `s.Nodes` is a Go slice, so by construction there cannot be an index out of range here.

Even If you can't provide the HTML at the point of failure, if you can provide the full stack trace and the full code of the function you pass to `Each`, I may be able to help you figure out what happens.

Martin
