### ISSUE TITLE
Find children

### ISSUE THREAD

**Issue by Luummii** [PuerkitoBio/goquery#285]
I'm sorry. Please, help me! How many children should return this function body.Children().Length() for this HTML code
https://play.golang.org/p/eHPfZghhguK

Returns 6. And can must 2? If not, why not?

**Comment by mna** [comment]
That's because the source html is malformed, and the parser auto-corrects it the same way an html5-compliant browser would. Notably, it has nested `<p>` elements, which after parsing and auto-correction are properly closed before a new one is started.

From MDN's doc on p (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p): 

> Paragraphs are block-level elements, and notably will automatically close if another block-level element is parsed before the closing </p> tag.

So the actual content of "body" after parsing ends up being:

```
<body>
  <p class="asd">
    more
    <a href="atte-test">content</a>
    </p>
  <p>test more p.
      </p>
  <h1>This is h1 header template lorem.</h1>
  <p></p>
  <p></p>
  <div class="foo here">
    <p>This <a href="/foo">
        <em>important</em> link class
        <br/> to foo
      </a> is here
    </p>
    <p>Call at <a href="mailto:sam@example.com">
        sam@example.com
      </a>
    </p>
    <div>
      <span>sam2@example.com</span>
      <div>
        <span>is the very good text</span>
      </div>
    </div>
    <p>
      Hello and <a href="">example.com</a>.
    </p>
    <em>are all valid. You can email &#34;john&#34; if you need me.</em>
    <h1>test h1 text</h1>
  </div>
</body>
```

I.e. 6 children.

Hope this helps!
Martin

**Comment by Luummii** [comment]
Thanks it helped!:)

**Comment by Luummii** [comment]
I'm sorry to bother you again. Interesting challenge. How can you wrap all the words in this example(https://play.golang.org/p/eHPfZghhguK) in tag - span. 

With the final result:
https://play.golang.org/p/GPDVGx6h0kH
