### ISSUE TITLE
get text after html node

### ISSUE THREAD

**Issue by wangsongyan** [PuerkitoBio/goquery#287]
is there a way to get text after html node?such as 'hangzhou',' join Jul 31, 2017'
```
<div class="description">
	<i class="octicon octicon-location"></i> hangzhou
	<i class="octicon octicon-mail"></i>
	<a href="mailto:example@hotmail.com" rel="nofollow">example@hotmail.com</a>
	<i class="octicon octicon-clock"></i> join Jul 31, 2017
</div>
```

**Comment by mna** [comment]
Hello,

Since those are text nodes, not elements (or "tags"), you can't get to them with a selector. What you can do is something like that:

```
        doc.Find(".description").Contents().Each(func(i int, s *goquery.Selection) {
		if goquery.NodeName(s) == "#text" {
			fmt.Printf(">>> (%d) >>> %s\n", i, s.Text())
		}
	})
```

I.e. `Contents` gets all nodes inside the description div (including text nodes), and `NodeName` gets either the "tag" for element nodes, or the special "#text" string for text nodes, so you can get to them that way.

Hope this helps!
Martin

**Comment by wangsongyan** [comment]
Thanks it helped!

**Comment by Ammar01muhammad** [comment]
Thanks
