### ISSUE TITLE
Not working correctly with file contains BOM

### ISSUE THREAD

**Issue by hanbang-wang** [PuerkitoBio/goquery#292]
[test.txt](https://github.com/PuerkitoBio/goquery/files/3092021/test.txt)

```go
file, e := ioutil.ReadFile(`test.txt`)
if e != nil {
	log.Fatal(e)
}
document, e := goquery.NewDocumentFromReader(bytes.NewReader(file))
if e != nil {
	log.Fatal(e)
}
fmt.Println(document.Find("body").Text())
```

In this given example, the code won't throw an error, meaning that this is correctly parsed. However, when trying to print body text, `goquery` would behave incorrectly and print all the texts. I think this is caused by DOM head in the file. However, the strange part is that the text is still able to pass the parsing.

**Comment by mna** [comment]
You have a [utf8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark) at the start of your file. If you change your line with this, it works fine:

```
	document, e := goquery.NewDocumentFromReader(bytes.NewReader(file[3:]))
```

(i.e. skip the BOM)

Hope this helps,
Martin

**Comment by hanbang-wang** [comment]
Yes, but the problem is that why it would parse without error but query incorrectly. It should either return an error if it cannot parse with BOM, or correctly query if parsed.

**Comment by mna** [comment]
That's because it does parse it. Goquery uses the `golang.org/x/net/html` package to parse the HTML, and that parser is based on the html5 spec which is made to be very lenient, and as such, it will successfully parse pretty much anything you throw at it, automatically correcting/adjusting tags along the way. Relevant: http://trevorjim.com/a-grammar-for-html5/
