### ISSUE TITLE
`<p><div></div></p>` get incorrect document

### ISSUE THREAD

**Issue by surpassly** [PuerkitoBio/goquery#299]
```go
cont := "<p><div></div></p>"
d, _ := goquery.NewDocumentFromReader(strings.NewReader(cont))
cont, _ = d.Find("body").Html()
fmt.Println(cont)
```
`<p><div></div></p>` become `<p></p><div></div><p></p>`

**Comment by mna** [comment]
Hello,

That's because the original document is invalid, p element cannot contain
other block elements (like div):
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

So the html parser automatically tries to fix the document (following the
html5 parser rules) and generates the resulting document.

Martin

**Comment by surpassly** [comment]
Thank you very much!
