### ISSUE TITLE
How to select "parent > child"?

### ISSUE THREAD

**Issue by divan** [PuerkitoBio/goquery#309]
I'm trying to parse a table, that has another tables inside it's cells. Simplied version is this:
```html
<table>
  <tr>
    <td>Foo1</td>
    <td>
      <table><tr><td>Bar1</td></tr></table>
    </td>
  <tr>
  <tr><td>Foo2</td><td><table><tr><td>Bar2</td></tr></table></td><tr>
  <tr><td>Foo3</td><td><table><tr><td>Bar3</td></tr></table></td><tr>
</table>
```
My selector looks like
```go
doc.Find("table tr").Each(func(idx int, rowhtml *goquery.Selection) {
        fmt.Println("Cell: ", idx, rowhtml.Text())
```
and the result I'm getting is:
```
Cell:  0
    Foo1

      Bar1


Cell:  1 Bar1
Cell:  2

Cell:  3 Foo2Bar2
Cell:  4 Bar2
Cell:  5

Cell:  6 Foo3Bar3
Cell:  7 Bar3
Cell:  8
```

which is not what I want.

As I understand, the direct child selector should here (https://api.jquery.com/child-selector/) but it seems to be unsupported by this library.

Is there a way to select only direct children and all down the tree?

**Comment by mna** [comment]
Hello Ivan, 

The result is correct given the input, note that your html is incorrect as it doesn't have closing `</tr>` tags (it has empty `<tr>` instead, which I assume you meant to be `</tr>` instead).

With the proper html, you'd get:

```
Cell:  0
    Foo1

      Bar1


Cell:  1 Bar1
Cell:  2 Foo2Bar2
Cell:  3 Bar2
Cell:  4 Foo3Bar3
Cell:  5 Bar3
```

I'm not clear on what you'd want to achieve, though? I'm gonna guess you don't want the inner tables as a separate result? The direct child selector works, it's just that once parsed into a goquery document, the html is automatically fixed by adding `<tbody>` nodes around the `<tr>`s, so if you want only direct children rows of table, you'd need to use `doc.Find("table > tbody > tr")`. But you'd still get the inner table as well as the outer table, because it still applies - i.e. the rows in the inner tables are also direct children of table and tbody, so you end up with the same result.

I don't know how to help you in this case as I don't know enough about what you're trying to do and what the real html looks like, but one option if the outer table is a direct child of the body is to use `doc.Find("body > table > tbody > tr")`. That will grab only the rows of the outer table, e.g.:

```
Cell:  0
    Foo1

      Bar1


Cell:  1 Foo2Bar2
Cell:  2 Foo3Bar3
```

Hope this helps,
Martin

**Comment by divan** [comment]
@mna thank you so much for the quick and elaborate answer. You're right, there is a mistake in the html, but that's simply because I wrote it quickly manually for the demo purposes.

Your hint about `tbody` tag was a missing piece – now the selector works as expected. Example you gave is exactly what I wanted to achieve.

Thank you so much!
