### ISSUE TITLE
When running 20 goroutines, the ram uses go upwards and upwards

### ISSUE THREAD

**Issue by cyantarek** [PuerkitoBio/goquery#317]
Hi,

When running goquery inside many goroutines, the RAM uses goes upward and upward.

Here's the pprof heap profile: https://imgur.com/a/gKUT79Y

What's wrong here?

**Comment by mna** [comment]
Hello Cyan,

From the pprof we can't tell much except that you seem to parse many documents (the net/html parse method) and holding on to them so they are not GCd. There's no indication of a problem with goquery in this image, it's the net/html parser that uses that memory and it's likely just because it parses multiple and/or big documents - a parsed document is represented by a tree of nodes in memory, so that will use some space, roughly proportional to the size of the DOM.

Martin

**Comment by cyantarek** [comment]
Yeah, I'm parsing long list of documents. After I done with the doc, it should be GCd. But why it's not GCd? And what to do in this situation?

**Comment by mna** [comment]
How are you monitoring your memory usage? And over what period of time? The GC doesn't necessarily return memory to the OS immediately.
