### ISSUE TITLE
can't get img html

### ISSUE THREAD

**Issue by axiaoxin** [PuerkitoBio/goquery#328]
```
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	html := `<div class="x">
	<a>
		<img class="a" src="111">
		
		<img class="yyy" src="222">
		<p>xxxxx</p>
	</a>
	<a>
		<img class="a" src="111">
		
		<img class="yyy" src="222">
		<p>yyyy</p>
	</a>
</div>
`

	dom, err := goquery.NewDocumentFromReader(strings.NewReader(html))
	if err != nil {
		log.Fatalln(err)
	}

	dom.Find(".x img").Each(func(i int, selection *goquery.Selection) {
		fmt.Println(selection.Html())
	})
}
```

print:

```
 <nil>
 <nil>
 <nil>
 <nil>
```

**Comment by mna** [comment]
Hello,

First of all, thanks for providing a complete, reproducible and runnable example, makes it that much easier to give a response.

The problem here is that you're printing the "inner" html of each selection, and since you've selected the `<img>` elements, there's no inner html (the img tag doesn't have any children). You'll see that your code works otherwise if you change `selection.Html()` with `goquery.OuterHtml(selection)`:

```
<img class="a" src="111"/> <nil>
<img class="yyy" src="222"/> <nil>
<img class="a" src="111"/> <nil>
<img class="yyy" src="222"/> <nil>
```

(the `<nil>` second value is the error value that is returned by `OuterHtml`).

Hope that helps,
Martin

**Comment by axiaoxin** [comment]
@mna Thank you very much for your reply!
