### ISSUE TITLE
EachWithBreak returns the original selection object instead of the current selection object

### ISSUE THREAD

**Issue by ragunathjawahar** [PuerkitoBio/goquery#389]
```go
// EachWithBreak iterates over a Selection object, executing a function for each
// matched element. It is identical to Each except that it is possible to break
// out of the loop by returning false in the callback function. It returns the
// current Selection object.
func (s *Selection) EachWithBreak(f func(int, *Selection) bool) *Selection {
  for i, n := range s.Nodes {
    if !f(i, newSingleSelection(n, s.document)) {
      return s
    }
  }
  return s
}
```

As per the documentation, if I have a list of `link` objects for instance. `EachWithBreak` should return only the first matching `link` object. Not the original list. Am I missing something here?

**Comment by mna** [comment]
Hello,

The return value of `EachWithBreak` is the same `*Selection` that was used to call the method, so yes it should return the original list. The break part is only to control how many times the function provided as argument to `EachWithBreak` will be called (i.e. if the original selection has 10 elements and you return false from the function passed as argument after 5 elements, it will not be called for the remaining 5, but the Selection returned from `EachWithBreak` will still be the original selection with 10 elements).

If you have a proposal/PR to clarify the documentation, I'd be happy to make it clearer (maybe specifying after `current Selection object` that this is the selection on which the method was called?).

Hope this helps!
Martin

**Comment by ragunathjawahar** [comment]
Hello Martin,

I am trying to understand the intention behind this API. We have `Each` and `EachWithBreak`. The difference I see in both the cases is the efficiency aspect. While `Each` will go though every element whereas `EachWithBreak` returns early. In case if I am interested in a particular selection, the mechanisms to retrieve the selection I am interested in is the same regardless of which function I call. I am trying to understand perhaps there is a `EachWithReturn` API, that can return the selection I am interested in. I guess `FilterFunction` gives me what I am looking for at the moment.

**Comment by mna** [comment]
Hey Ragunath,

The reason for the two functions is historical, `Each` came first but the lack of way to exit early was an oversight, which is why `EachWithBreak` was then added (see https://github.com/PuerkitoBio/goquery/issues/13). You're correct that the only difference is the efficiency in breaking out of the loop early.

For your intended use-case, where you want to use a function to control what gets selected, this is not the right approach. I do believe that `FilterFunction` (https://pkg.go.dev/github.com/PuerkitoBio/goquery#Selection.FilterFunction) is the right one for what you want to do.

Have fun!
Martin

**Comment by ragunathjawahar** [comment]
Thank you very much for the explanation Martin :) FilterFunction is what I want.
