### ISSUE TITLE
<head> tag not parsed correctly

### ISSUE THREAD

**Issue by HmzAli** [PuerkitoBio/goquery#395]
```
doc, err := goquery.NewDocumentFromReader(bytes.NewReader([]byte(`
		<html>
			<body>
				<head>
					<meta name="twitter:description" content="Homepage">
					<link rel="stylesheet" media="screen" href="/path/to/file" />
				</head>
			</body>
		</html>`)))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(doc.Html())
```

**Expected output:**
```
<html>
			<body>
				<head>
					<meta name="twitter:description" content="Homepage">
					<link rel="stylesheet" media="screen" href="/path/to/file" />
				</head>
			</body>
		</html>
```

**Actual output:**

```
<html><head></head><body>

                                        <meta name="twitter:description" content="Homepage"/>
                                        <link rel="stylesheet" media="screen" href="/path/to/file"/>


                </body></html> <nil>
```

**Comment by mna** [comment]
Hello Hamza,

That's because the source html is invalid, and the html5 parser (as per the spec) tries very hard to accept everything thrown at it - in this case it notices that there's an invalid `<head>` element in the `<body>` part of the doc and removes it, keeping the rest of the elements.

If you have control over the html, you'll want to move the head part right under the `<html>` tag, above (and outside) the `<body>` tag (as in the actual output in your example).

Hope this helps!
Martin
