### ISSUE TITLE
Help needed: How to extract the text from this div

### ISSUE THREAD

**Issue by StefMa** [PuerkitoBio/goquery#402]
Hey,

sorry if I ask for help here. In case I should better ask somewhere else, feel free to simply close it 😅 .

I want to get the **rating number** for the Google Play Store.
Like: https://play.google.com/store/apps/details?id=com.germanwings.android 
**4,5** (or **4.5** = depending on the langauge).

My code is the following:
```go
doc.Find(".BHMmbe").EachWithBreak(func(i int, s *goquery.Selection) bool {
	selectorResult = selector(i, s)
	return selectorResult == ""
})
```
My `selector(i,s)` function is a simple:
```go
x  := s.Text()
log.Println("x -> " + x)
return x
```

But for some reasons, this doesn't work.
Can someone give me a hint why this doesn't work and how it should look like to work?
The HTML parts looks (even with JavaScript disable) like that:
```html
[...]
<c-wiz jsrenderer="JV1xu" jsshadow jsdata="deferred-i25" data-p="%.@.[&quot;com.germanwings.android&quot;,7]]" data-node-index="3;0" jsmodel="hc6Ubd" c-wiz><div class="K9wGie"><div class="BHMmbe" aria-label="Mit 4,5 von fünf Sternen bewertet">4,5</div><div class="LvvOW">
[...]
```

I tried it also in the Go-Playground, there it worked as I expected 🙈 
https://go.dev/play/p/oP5XieAX4Z1

Thanks in advance!

**Comment by mna** [comment]
Hello,

I tried it, after running

```
$ curl -o data.html https://play.google.com/store/apps/details?id=com.germanwings.android
```

The program:

```
func main() {
	b, err := os.ReadFile("data.html")
	if err != nil {
		log.Fatal(err)
	}
	doc, err := goquery.NewDocumentFromReader(bytes.NewReader(b))
	if err != nil {
		log.Fatal(err)
	}
	doc.Find(".BHMmbe").EachWithBreak(func(i int, s *goquery.Selection) bool {
		fmt.Println(s.Text())
		return true
	})
}
```

And it works, it prints only `4.7`, but that's normal as there's only one ".BHMmbe" in the html (at least at the time I curl'd it).

Not sure what the issue might be, but it looks likely it's due to a difference between your actual code and the simplified version you posted in the playground. If you can get a minimal program that reproduces the issue with a static HTML input, that'd help figuring it out. One thing I noticed is that in `EachWithBreak` you return `return selectorResult == ""`, which would exit the loop as soon as the result is not an empty string (i.e. as soon as you get a rating), that might not be what you want if there's more than one rating in the page? But in any case, it should at least print one rating before exiting.

Hope this helps!
Martin

**Comment by StefMa** [comment]
Thanks for the quick answer @mna.
Seems you're right. Somehwat is breaking my "production code".
I just created a sample project with the following code, and it worked:
```go
package main

import (
  "bytes"
  "fmt"
  "io"
  "log"
  "net/http"

  "github.com/PuerkitoBio/goquery"
)

func main() {
	x, _ := fetchWebsite("https://play.google.com/store/apps/details?id=com.germanwings.android")
	printRating(x)
}

func fetchWebsite(url string) ([]byte, bool) {
	resp, err := http.Get(url)
	if err != nil {
		log.Println(err)
		return nil, false
	}
	if resp.StatusCode != 200 {
		log.Printf("status code error: %d %s", resp.StatusCode, resp.Status)
		return nil, false
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Println(err)
		return nil, false
	}
	return bodyBytes, true
}

func printRating(x []byte) {
	html_code := bytes.NewReader(x)
	doc, _ := goquery.NewDocumentFromReader(html_code)
	doc.Find(".BHMmbe").EachWithBreak(func(i int, s *goquery.Selection) bool {
		fmt.Println(s.Text())
		return true
	})
}
```

I wil investiagte a bit more why my production doesn't work... 🤔

**Comment by StefMa** [comment]
Hi @mna,

thanks again for you're help.
I found out that this isue has nothing to do with the library or something.
For strange reasons, the server just get a different HTML for the Play Store entry than my local machine.
I have no idea why 😨 .

Anyways. Thankls for the help.
