### ISSUE TITLE
go get error: go.mod file not found in current directory

### ISSUE THREAD

**Issue by anujgoyal** [PuerkitoBio/goquery#422]
What are the instructions for go install ?

```
$ brew install go

$ go version
go version go1.18.3 darwin/arm64

$ go get github.com/PuerkitoBio/goquery
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

**Comment by mna** [comment]
Hello,

This is unrelated to goquery, it is how the `go` toolchain works - since Go1.16 (https://go.dev/blog/go116-module-changes), `go get` only works in module mode (see https://go.dev/blog/using-go-modules for details) so you need to run it in a directory that has a `go.mod` file. Run `go mod init` in your directory, and then you can `go get` the modules you want to use in your app.

Hope this helps,
Martin
