### ISSUE TITLE
html.Parse is messing html file i need to change

### ISSUE THREAD

**Issue by Bibi40k** [PuerkitoBio/goquery#428]
Hi,
I'm trying to rewrite [foundation/inky](https://github.com/foundation/inky) project in Golang. This tool seems to be perfect for this job but as Martin said 3 years ago x/net/html parser is "messing the code"

i've found this old issue: https://github.com/PuerkitoBio/goquery/issues/283

Is there any solution nowadays to manipulate html docs without any extra changes from the parser ?

Thanks

**Comment by mna** [comment]
Hello,

The `x/net/html` parser can indeed alter the tree of nodes, but I wouldn't call that "messing" it, it is part of the html5 parser specification (mentioned in the parser's comment: https://pkg.go.dev/golang.org/x/net/html#Parse) and that's how browsers and compliant parsers can accept imperfectly-formatted html and still make something reasonable out of it.

That being said, you haven't shown a minimal example that reproduces the issue you're facing, but from what I gather looking at the inky project, you want to get html that looks something like that?

```
<row>
  <columns large="6"></columns>
  <columns large="6"></columns>
</row>
```

From what I know, this is not even html, there is no `<row>` HTML element AFAIK (and MDN seems to agree with me). You can't expect good, consistent results from non-html or xml with goquery. However this (the second example in inky's readme) is valid html:

```
<table class="row">
  <tbody>
    <tr>
      <th class="small-12 large-6 columns first">
        <table>
          <tr>
            <th class="expander"></th>
          </tr>
        </table>
      </th>
      <th class="small-12 large-6 columns first">
        <table>
          <tr>
            <th class="expander"></th>
          </tr>
        </table>
      </th>
    </tr>
  </tbody>
</table>
```

If you parse it with goquery and print the resulting document, you get a complete html document due to the html5 parser's rules:

```
const data = `
<table class="row">
  <tbody>
    <tr>
      <th class="small-12 large-6 columns first">
        <table>
          <tr>
            <th class="expander"></th>
          </tr>
        </table>
      </th>
      <th class="small-12 large-6 columns first">
        <table>
          <tr>
            <th class="expander"></th>
          </tr>
        </table>
      </th>
    </tr>
  </tbody>
</table>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		panic(err)
	}
	fmt.Println(goquery.OuterHtml(doc.Selection))
}

// Prints:
// <html><head></head><body><table class="row">
//  <tbody>
//    <tr>
//      <th class="small-12 large-6 columns first">
//        <table>
//          <tbody><tr>
//            <th class="expander"></th>
//          </tr>
//        </tbody></table>
//      </th>
//      <th class="small-12 large-6 columns first">
//        <table>
//          <tbody><tr>
//            <th class="expander"></th>
//          </tr>
//        </tbody></table>
//      </th>
//    </tr>
//  </tbody>
//</table>
//</body></html>
```

The table is still there, just wrapped in `<html><body>`. So if you know that's what you need and you don't want the wrapping elements, you could just select that element after loading the document with goquery, and use this as your "partial html" for inky.

I.e. :
```
fmt.Println(goquery.OuterHtml(doc.Find("table").First()))
```

Prints:
```
<table class="row">
  <tbody>
    <tr>
      <th class="small-12 large-6 columns first">
        <table>
          <tbody><tr>
            <th class="expander"></th>
          </tr>
        </tbody></table>
      </th>
      <th class="small-12 large-6 columns first">
        <table>
          <tbody><tr>
            <th class="expander"></th>
          </tr>
        </tbody></table>
      </th>
    </tr>
  </tbody>
</table>
```

Hope this helps,
Martin

**Comment by Bibi40k** [comment]
Thank you very much for your kind example.

I know this approach, i was "afraid" to try it because they invented a lot of non-html elements so code will probably become pretty messy.

Inky is made for email templating so they use HTML1 afaik and my biggest fear and question is that `x/net/html` would also make HTML5 compliant my partials (with any kind of changes) or is it going to just wrap everything into `<html><body>` ? If it does, i can't keep track of things, if not... then your suggestion might work.

Anyway, i thought there is a way to set `x/net/html` not to affect code in any way, which seems there isn't.

**Comment by mna** [comment]
> i thought there is a way to set x/net/html not to affect code in any way, which seems there isn't.

No, indeed, that package is an html5-compliant parser and will try to parse your input as such. If your input is not meant to be html, it's unlikely to do what you want it to do, and if so it's just by chance and will be a fragile solution.
