### ISSUE TITLE
how to get values not it the html tag eg.span tag

### ISSUE THREAD

**Issue by davidAg9** [PuerkitoBio/goquery#433]
I have an issue where the value I want to get isn't in the span tag but beside it 
`   <span class="fas fa-user"></span> Published By <a href="mailto:ur@gctu.edu.gh"> University Relations Directorate</a> |
                            <span class="fas fa-calendar">  </span>     Monday October 3, 2022  |   <span class="fas fa-clock"></span> 2:27 pm`

how do I go about writing it

_Originally posted by @davidAg9 in https://github.com/PuerkitoBio/goquery/issues/298#issuecomment-1306141148_

**Comment by mna** [comment]
Hello David, 

You can see an example of how to get that here: https://github.com/PuerkitoBio/goquery/issues/287#issuecomment-471043149

Basically, what you can do is get the parent node via a selector, and then iterate over the selection returned by [`Contents()`](https://pkg.go.dev/github.com/PuerkitoBio/goquery#Selection.Contents) (as it is the only one that selects not only HTML elements but all types of nodes, like text and comments) and look for the text nodes to extract the text. What you have there is somewhat weird HTML (in the sense that usually, the `span`s are there to hold some text, but here it is empty - though with CSS class - and the text is in-between), but anyway sometimes we have to work with broken HTML so that may be your case.

For example:

```
const data = `
<html>
<body>
	<p>
		<span class="fas fa-user"></span> Published By <a href="mailto:ur@gctu.edu.gh"> University Relations Directorate<!--Henry Amoah--></a> | <span class="fas fa-calendar"> </span> Monday October 3, 2022 | <span class="fas fa-clock"></span> 2:27 pm
	</p>
</body>
</html>
`

func main() {
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(data))
	if err != nil {
		log.Fatal(err)
	}

	doc.Find("p").Contents().Each(func(i int, s *goquery.Selection) {
		if goquery.NodeName(s) == "#text" {
			fmt.Printf(">>> (%d) >>> %s\n", i, s.Text())
		}
	})
}
```

This would print (note that it doesn't get the "University Relations Directorate" as it is not a "free text" element, it is text inside the `<a>` element):
```
>>> (0) >>> 
		
>>> (2) >>>  Published By 
>>> (4) >>>  | 
>>> (6) >>>  Monday October 3, 2022 | 
>>> (8) >>>  2:27 pm
```

Hope this helps!
Martin

**Comment by davidAg9** [comment]
Thanks you very much
