### ISSUE TITLE
How can i get the elements inside of iframe?

### ISSUE THREAD

**Issue by jexists** [PuerkitoBio/goquery#438]
"How can I obtain the elements within an iframe, similar to the chrome.switch_to.frame() method in Python?"

**Comment by mna** [comment]
Hello,

Please provide a runnable, minimal example of a program that illustrates the issue (including the html). I believe that `iframe`s embed a different document, so it's very likely that the html you parse with goquery doesn't have access to whatever is in the iframe, you'd probably need something that mimics a browser for that, and even then I'm not sure if the parent document can access inside the iframe. I don't know the python method you refer to.

Martin

**Comment by jexists** [comment]
```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

func main() {
	getNickname()
}

func getNickname() {
	res, err := http.Get("https://cafe.naver.com/jexists/1")
	checkErr(err)
	checkCode(res)

	defer res.Body.Close()

	doc, err := goquery.NewDocumentFromReader(res.Body)
	checkErr(err)
	h, err := goquery.OuterHtml(doc.Find("#cafe_main .nick_box .nickname"))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(h) // nil


	return
}

func checkErr(err error) {
	if err != nil {
		log.Fatalln(err)
	}
}

func checkCode(res *http.Response) {
	if res.StatusCode != 200 {
		log.Fatalln("Request Fail Status: ", res.StatusCode)
	}
}
```

**Comment by mna** [comment]
Yeah pretty much the whole page is dynamic, the `#cafe_main` element does not even exist in the html. You need to look into a browser-like solution that will execute the javascript in the page so that dynamic html elements are created as they are when the page is loaded in a browser. This is not supported directly by goquery, but the community has documented some options in the wiki: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages

Hope this helps,
Martin
