### ISSUE TITLE
GoQuery using up excess memory

### ISSUE THREAD

**Issue by syllith** [PuerkitoBio/goquery#445]
Hello, I am creating an application that pulls loads of data from a website, parses it, then moves onto the next website. I noticed my memory usage was slowly increasing indefinitely over time and after using pprof to identify the problem, GoQuery was using 30-45% of my memory. Since this takes nearly 12 hours to reach this point, I don't know 100% if GoQuery is the problem. But I figured it wouldn't hurt to run it by you to see what you think. Here's how I'm using it:

```
doc, err := goquery.NewDocumentFromReader(strings.NewReader(body))
if err != nil {
	return
}
```
Now I do see in the documentation is says this: "It does not check if the reader is also an io.Closer, the provided reader is never closed by this call. It is the responsibility of the caller to close it if required."

I am calling strings.NewReader(body), so perhaps the problem is that I'm not closing out of this reader? I tried making it its own variable and seeing if there was a method to close it but there doesn't seem to be any. I also see that "doc" doesn't have a way to close out either. Could you please shed some light on how GoQuery disposes of memory and if you see any reason that GoQuery would be using so much memory? Thank you for any assistance. This has been a problem for a long time and I don't know where else to look from here.

**Comment by mna** [comment]
Hello,

You say you have run the profiler, do you have the graph that you can share? Considering your app seems to heavily parse pages, it’s not necessarily indicative of a goquery issue that it uses a good chunk of the memory, but maybe there’s something that would stand out. 

The strings.Reader is not a closable reader, so that shouldn’t be the problem. Do you notice the memory growing and then sharply dropping at regular intervals? That’s how it typically looks, when the GC collects unreachable objects. Goquery does use memory by design, due to its immutable selections approach, but the underlying html nodes are the same for a given document throughout its use. As long as you don’t hold onto goquery objects after their use, it would be garbage collected. 

It will be pretty hard to find an issue/identify that it’s due to goquery without more details and ideally a way to reproduce, but the pprof graph could help. Also, what do you qualify “excess memory”, do you have some numbers just to double-check that it is indeed excessive?

Martin

**Comment by syllith** [comment]
Thank you for the response. I've actually made a discovery while doing some more testing. It turns out the problem was related to the way I was excessively calling it. I had a flaw in my logic that would call http.Client.Get() more than expected, which would then parse it with goquery. The real problem was hiding underneath and not actually a problem with goquery at all. Thank you for the information though, it is useful. Appreciate your time.
