### ISSUE TITLE
QueryParams in links are encoded incorrectly

### ISSUE THREAD

**Issue by marwonline** [PuerkitoBio/goquery#448]
Hey there,

thanks for your effort in building & maintaining this library. 

I've a bug report: The query parameters on links are encoded incorrectly when passing though the library (Code attached below).

In:  
`<a href="https://example.org/test?a=b&c=d">Link</a>`
Out:
`<a href="https://example.org/test?a=b&amp;c=d">Link</a>`

The problem is that the `&` sign is encoded in the `href` attribute which breaks the semantic.

Go: `go1.20.1 linux/amd64`
Version: `1.8.1`

<details>
<summary>Test program</summary>

```
package main

import (
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"strings"
)

func main() {
	htmlStr := `
<html>
<body>
    <a href="https://example.org/test?a=b&c=d">Link</a>
	a&nbsp;b
</body>
</html>
`
	doc, _ := goquery.NewDocumentFromReader(strings.NewReader(htmlStr))
	o, _ := doc.Html()
	fmt.Println(o)
}
```

</detaisl>

**Comment by mna** [comment]
Hello Martin,

Thanks for providing an example program to reproduce what you thought was the issue. It turns out this is correct, HTML attributes must be escaped this way (see https://stackoverflow.com/a/9189067/1094941 and the template/html package in the Go stdlib properly handles this encoding too as mentioned in https://pkg.go.dev/html/template#hdr-Contexts). When you read the attribute via an appropriate method to do so (in Goquery, `Selection.Attr` or `Selection.AttrOr`), it will properly decode the escaped string and return the correct URL. For example:

```
func main() {
	htmlStr := `
<html>
<body>
    <a href="https://example.org/test?a=b&c=d">Link</a>
	a&nbsp;b
</body>
</html>
`
	doc, err := goquery.NewDocumentFromReader(strings.NewReader(htmlStr))
	if err != nil {
		log.Fatal(err)
	}
	a := doc.Find("a")
	fmt.Println(goquery.OuterHtml(a))
	fmt.Println(a.AttrOr("href", "-"))
}
// Prints:
// <a href="https://example.org/test?a=b&amp;c=d">Link</a> <nil>
// https://example.org/test?a=b&c=d
```

Hope this helps,
Martin
