### ISSUE TITLE
If an id attribute contains dots tag will not be found

### ISSUE THREAD

**Issue by gitusercode** [PuerkitoBio/goquery#453]
I'm trying to get div using the following selector: "div#go1.20.0", but this selector doesn't have results.  The length method in the following code will return 0:
`doc.Find("div#go1.21.0").Length()`// length returns 0
html:
```
<div class="toggleVisible" id="go1.21.0">
...
</div>
```

**Comment by mna** [comment]
Hello,

That's because in CSS selectors, the dot indicates a class to be applied to the node, so `doc.Find("div#go1.21.0")` would look for a div with id `go1` and classes `21` and `0`. You have to escape the dot if you want it to be recognized as the id as a whole, as [documented in the MDN article on `id`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id):

> For example, . has a special meaning in CSS (it starts a [class selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors)). While valid, unless you are careful to escape it when used as part of a CSS selector, it won't be recognized as part of the element's id.

So something like this will work:

```
doc.Find("#go1\\.21\\.0")
```

Hope this helps, 
Martin

**Comment by gitusercode** [comment]
It works, thank you
