### ISSUE TITLE
I am sorry, i can't find. May be some error.

### ISSUE THREAD

**Issue by gravitymir** [PuerkitoBio/goquery#455]
I can't find element "#page-manager"
page https://www.youtube.com/@BallisticHighSpeed/videos
Element "#page-manager" have on page

```go
res, err := http.Get("https://www.youtube.com/@BallisticHighSpeed/videos")
if err != nil {
		log.Fatal(err)
	}
	defer func(Body io.ReadCloser) {
		err := Body.Close()
		if err != nil {

		}
	}(res.Body)
        if res.StatusCode != 200 {
		log.Fatalf("status code error: %d %s", res.StatusCode, res.Status)
	}

	// Load the HTML document
	doc, err := goquery.NewDocumentFromReader(res.Body)


        if err != nil {
		log.Fatal(err)
	}

        doc.Find("#page-manager").Each(
		func(i int, selection *goquery.Selection) {
			fmt.Println(i)
		})
```

My finnaly select dosent work  "#page-manager > ytd-browse > ytd-two-column-browse-results-renderer #primary #contents ytd-rich-grid-row #contents ytd-rich-item-renderer #content ytd-rich-grid-media #dismissible #details #meta h3 a[href]"
in browser console it works
$$(
'#page-manager > ytd-browse > ytd-two-column-browse-results-renderer #primary #contents ytd-rich-grid-row #contents ytd-rich-item-renderer #content ytd-rich-grid-media #dismissible #details #meta h3 a[href]'
).map((e) => e.href.replace('https://www.youtube.com/watch?v=', '').replace(/\=\d{1,5}s/, '').replace(/\&t/, '')).reverse();

**Comment by mna** [comment]
Hello,

Youtube pages are heavily javascript-based, if you get the page's static html content using e.g. `curl -o page.html https://www.youtube.com/@BallisticHighSpeed/videos` and search the resulting `page.html` file, you'll see that the `page-manager` id is not there.

It works inside the browser console because javascript is running and that elements gets added via the scripts.

There's a section in the wiki on how to handle javascript-based pages: https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks#handle-javascript-based-pages (note that it is community-provided, I'm not familiar with this approach).

Hope this helps,
Martin
