### ISSUE TITLE
tagName of node

### ISSUE THREAD

**Issue by tobstarr** [PuerkitoBio/goquery#67]
Is there a shortcut for getting the tag name of the first node of a selection (similar to http://api.jquery.com/prop/ with `tagName`).

Currently I use something like this:

```
if n := s.Get(0); n.Type == html.ElementNode && n.Data == "div" {
...
}
```

but a shorthand might be handy.

**Comment by PuerkitoBio** [comment]
That's a very interesting point. I don't think `prop` should be added, because it would be confusing that it just works for `tagName` (there's no DOM, so there are no other "properties"), but then there's no easy way to get the tag name of an element, as you mention.

I don't have a good idea right now about how to add this, or if this should even be added. I'm certainly not crazy about adding something that is not in jQuery, so that's a con about special-casing the tagname via some non-"standard" function, and I think adding `prop` is misleading as I just said... I'm open to suggestions, and I'll let that sink in a little bit, see if we find some elegant way to support this.

**Comment by tobstarr** [comment]
Thnak you for the quick response. I was just curious I am not missing something.

I am happy with my "workaround", would that be the recommended way to do this? I also have a `len(s.Nodes) > 0` check before that call but that should be a case whould not happen (I do this using a selection from `.Children()`).

**Comment by PuerkitoBio** [comment]
Yeah, with the current state of things, your workaround is the way to do it.

**Comment by PuerkitoBio** [comment]
I think I'll pass for now, will reconsider if it becomes a frequently-requested feature, closing.

**Comment by Acidic9** [comment]
+1 for this, It would be nice to see the tag name of an element.
