### ISSUE TITLE
Parsing Response and keeping it open

### ISSUE THREAD

**Issue by amlwwalker** [PuerkitoBio/goquery#74]
goquery.NewDocumentFromResponse(resp) closes the response body.

I am writing a proxy that removes offensive words from pages. I wanted to use goquery to parse the document and swap out specific words however I think because it closes the body the page is never loaded in the browser:
This:
```
func ParsePage() {
	proxy := goproxy.NewProxyHttpServer()
	proxy.OnResponse().DoFunc(func(resp *http.Response, ctx *goproxy.ProxyCtx) *http.Response {
		goquery.NewDocumentFromResponse(resp)
		return resp
	})
	log.Fatalln(http.Serve(listener, proxy))
}
```
means no document ever makes it back to the browser. Removing the goquery line works fine. I want to manipulate the document and then return the manipulated response. 
Am I missing something?

**Comment by PuerkitoBio** [comment]
Hi Alex,

Yes, `NewDocumentFromReader` closes the body because the body is consumed on return anyway, so you wouldn't be able to do what you want.

If you want to potentially modify the body before returning it, then you have no choice but to buffer it somehow (because goquery/the underlying http parser requires the document to be fully loaded in memory to parse the nodes).

Martin
