### ISSUE TITLE
Can't parse tag: <foo>bar/</foo>

### ISSUE THREAD

**Issue by pagedegeek** [PuerkitoBio/goquery#84]
http://play.golang.org/p/BiXcmMg9B9

```go
package main

import (
	"github.com/PuerkitoBio/goquery"
	"log"
	"net/http"
)

func main() {
	req, err := http.NewRequest("GET", "http://www.medialab.sciences-po.fr/feed/", nil)
	if err != nil {
		log.Fatal(err.Error())
	}

	httpClient := &http.Client{}
	resp, err := httpClient.Do(req)
	if err != nil {
		log.Fatal(err.Error())
	}
	defer resp.Body.Close()

	doc, err := goquery.NewDocumentFromResponse(resp)
	if err != nil {
		log.Fatal(err.Error())
	}

	doc.Find("item").Each(func(idx int, s *goquery.Selection) {
		// <title>Contropedia &#8211; the analysis and visualization of controversies in Wikipedia articles</title>
		title := s.Find("title").First().Text()
		log.Printf("title: %s", title)
		// <link>http://.../</link>
		link := s.Find("link").First().Text() // bug
		log.Printf("link: %s", link)
	})
}

```

**Comment by PuerkitoBio** [comment]
Hi Sam,

I believe this is because you are not parsing HTML. Goquery uses the net/html Go parser, which is kind of strict/smart about the tags, and the <link> tag is a valid html tag, but one that cannot/should not have content in a valid html document (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link). The same happens if the text is inside e.g. `base` (another empty element), but works fine inside e.g. `title` (a non-empty element).

I would suggest an RSS parser for your needs (haven't tried any in Go, but godoc lists a bunch of them: http://godoc.org/?q=rss).

Hope this helps,
Martin

**Comment by pagedegeek** [comment]
Ok thanks :)
