### ISSUE TITLE
.OuterHtml() property

### ISSUE THREAD

**Issue by lmmx** [PuerkitoBio/goquery#96]
I was just using this and needed the outer HTML, so had to implement a type alias as a bit of an awkward workaround. Could I suggest adding an `OuterHtml()` function to property.go (unless this was deliberately avoided)?

What I went with:

```go
type ParserSelection goquery.Selection

// Implemented from equivalent for InnerHtml (see .Html() in goquery/property.go)
func (s *ParserSelection) OuterHtml() (ret string, e error) {
        // Since there is no .outerHtml, the HTML content must be re-created from
        // the node using html.Render
        var buf bytes.Buffer
        if len(s.Nodes) > 0 {
                c := s.Nodes[0]
                e = html.Render(&buf, c)
                if e != nil {
                        return
                }
                ret = buf.String()
        }
        return
}
```

called as

```go
        doc.Find(selector).Each(func(i int, s *goquery.Selection) {
                // mask the Selection type
                mask := ParserSelection(*s)
                element, err := mask.OuterHtml()
                check(err)
                fmt.Printf(element)
        })
```

**Comment by PuerkitoBio** [comment]
Hello Louis,

Yeah the reason for not having it is basically because jquery doesn't have it (outerHtml being an available property on the native DOM element). I agree that with goquery, it's a bit more involved to get that data, with your implementation being the correct way to do this.

I'll take a better look at it, but it might very well make sense to add the method.

Thanks,
Martin
